# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ralose 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ralose".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Douglas F Shearer".freeze]
  s.date = "2018-05-25"
  s.email = "dougal.s@gmail.com".freeze
  s.executables = ["ralose".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ralose",
    "lib/ralose.rb",
    "lib/ralose/command.rb",
    "ralose.gemspec",
    "test/fixtures/sample.log",
    "test/helper.rb",
    "test/test_ralose.rb"
  ]
  s.homepage = "http://github.com/dougal/ralose".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Search Rails logs for a string - get all the log lines for matching requests.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.0.4"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
    else
      s.add_dependency(%q<rdoc>.freeze, ["~> 6.0.4"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
    end
  else
    s.add_dependency(%q<rdoc>.freeze, ["~> 6.0.4"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
  end
end

